[package]
name = "knapsack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spea2={path="../spea2"}
rand = "0.8.5"
